#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys


def factorize():
    """
    A function to search file and factorize the given set of numbers into two prime numbers (format n = p*q)
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for line_number in f:
                line_number = int(line_number)
                if line_number % 2 == 0:
                    print("{} = {} * {}".format(line_number, line_number // 2, 2))
                    continue

                for i in range(3, line_number // 2 + 1, 2):
                    if line_number % i == 0:
                        print("{} = {} * {}".format(line_number, line_number // i, i))
                        break
                else:
                    print("{} = {} * {}".format(line_number, line_number, 1))
    except IndexError:
        print("Usage: {} <filename>".format(sys.argv[0]))


factorize()
